### ISSUE TITLE
Allow custom features

### ISSUE THREAD

**Issue by HardcoreIOS** [squimer/DatePickerDialog-iOS-Swift#15] opened 2016-03-03 17:24 UTC
Please allow the user to have custom features. Like I want the background to have a blur when the picker view is presented, the pickerview's background to be a black instead of the default gray, and the pickerview's text's to be white instead of the default black!

**Comment by lfarah** [comment] 2016-07-19 19:10
Duplicate of #12

**Closed by lfarah** 2016-07-19 19:10 UTC
Labels: enhancement
