### ISSUE TITLE
DatePicker Dialog not showing

### ISSUE THREAD

**Issue by riazurcse** [squimer/DatePickerDialog-iOS-Swift#20] opened 2016-05-12 10:49 UTC
Hello Dear, 
I am using storyboard. If i set entry point using storyboard then dialog working fine. When i set rootViewController programmatically in AppDelegate, DatePickerDialog not working anymore.

window =  UIWindow(frame: UIScreen.mainScreen().bounds)
        window?.makeKeyAndVisible()
        
        storyboard = UIStoryboard(name: "Main", bundle: nil)
        
        let homeViewController = self.storyboard?.instantiateViewControllerWithIdentifier("HomeView") as? HomeViewController
        let userTypeController = self.storyboard?.instantiateViewControllerWithIdentifier("UserTypeView") as? UserTypeController
        
        if self.window != nil {
            
            let userDataExist = CommonUserFunction.isUserDataExist() as Bool
            
            if userDataExist == true {
                
                let navigationController:UINavigationController = storyboard!.instantiateInitialViewController() as! UINavigationController
                navigationController.viewControllers = [homeViewController!]
                
                self.window!.rootViewController = navigationController
            }
            else{
                
                let navigationController:UINavigationController = storyboard!.instantiateInitialViewController() as! UINavigationController
                navigationController.viewControllers = [userTypeController!]
                
                self.window!.rootViewController = navigationController
            }
        }

please Help...Thanks in advance...

**Comment by lfarah** [comment] 2016-07-19 18:57
Duplicate of #18

**Closed by lfarah** 2016-07-19 18:57 UTC
